title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo_image: 
favicon_image: 
apple_touch_icon_image: 
locale: en_us
author:
  facebook: facebook-page-handle
  twitter: twitter-handle-no-@
facebook:
  publisher: page-id
  admins: site-admin-facebook-profile-id
twitter:
  username: twitter-handle-no-@
google:
  analytics: code
gems:
- hawkins
markdown: kramdown
sass:
  sass_dir: assets/stylesheets
  style: compressed
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - hawkins
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
